name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:

  release:
    name: Prepare release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Make the compressed artifact
        uses: softprops/action-gh-release@v1
